/* Generated by wayland-scanner 1.16.0 */

/*
 * Copyright © 2018 Ilia Bozhinov
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface zwlr_foreign_toplevel_handle_v1_interface;

static const struct wl_interface *types[] = {
	NULL,
	&zwlr_foreign_toplevel_handle_v1_interface,
	&wl_seat_interface,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_output_interface,
	&wl_output_interface,
	&wl_output_interface,
};

static const struct wl_message zwlr_foreign_toplevel_manager_v1_requests[] = {
	{ "stop", "", types + 0 },
};

static const struct wl_message zwlr_foreign_toplevel_manager_v1_events[] = {
	{ "toplevel", "n", types + 1 },
	{ "finished", "", types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_foreign_toplevel_manager_v1_interface = {
	"zwlr_foreign_toplevel_manager_v1", 2,
	1, zwlr_foreign_toplevel_manager_v1_requests,
	2, zwlr_foreign_toplevel_manager_v1_events,
};

static const struct wl_message zwlr_foreign_toplevel_handle_v1_requests[] = {
	{ "set_maximized", "", types + 0 },
	{ "unset_maximized", "", types + 0 },
	{ "set_minimized", "", types + 0 },
	{ "unset_minimized", "", types + 0 },
	{ "activate", "o", types + 2 },
	{ "close", "", types + 0 },
	{ "set_rectangle", "oiiii", types + 3 },
	{ "destroy", "", types + 0 },
	{ "set_fullscreen", "2?o", types + 8 },
	{ "unset_fullscreen", "2", types + 0 },
};

static const struct wl_message zwlr_foreign_toplevel_handle_v1_events[] = {
	{ "title", "s", types + 0 },
	{ "app_id", "s", types + 0 },
	{ "output_enter", "o", types + 9 },
	{ "output_leave", "o", types + 10 },
	{ "state", "a", types + 0 },
	{ "done", "", types + 0 },
	{ "closed", "", types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_foreign_toplevel_handle_v1_interface = {
	"zwlr_foreign_toplevel_handle_v1", 2,
	10, zwlr_foreign_toplevel_handle_v1_requests,
	7, zwlr_foreign_toplevel_handle_v1_events,
};

